# Generated by Django 2.1.7 on 2019-04-01 05:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('polls', '0002_auto_20190401_1237'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quetion',
            new_name='Question',
        ),
    ]
