# Generated by Django 2.1.7 on 2019-03-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(verbose_name='time created')),
                ('updated_at', models.DateTimeField(verbose_name='time updated')),
            ],
        ),
    ]
